/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ProfileIcon = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/c3d199939e3bc0c52d924578df2b6e16162c56b9cbcd22c1882ee194f75abe7b?apiKey=ccf78d4ef6544615a01756b290b630ea&"
      alt="Profile icon"
      className="shrink-0 w-10 aspect-square"
    />
  );
};

export default ProfileIcon;
