/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchIcon = () => {
  return (
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/4cbba59b72fb3c187db2bc484bcc1affd507ab4d28589945660de509e1059473?apiKey=ccf78d4ef6544615a01756b290b630ea&"
      alt="Search icon"
      className="border-solid aspect-square border-[3px] border-black border-opacity-70 stroke-[3px] stroke-black stroke-opacity-70 w-[23px]"
    />
  );
};

export default SearchIcon;
